### ISSUE TITLE
Datasets?

### ISSUE THREAD

**Issue by yanghuidong** [marcotcr/lime-experiments#3]
Hi Marco,

I'm wondering, in order to actually run the experiments on our end, where we can get the "multi_polarity_" datasets?

Thank you!

**Comment by marcotcr** [comment]
[Here they are](https://www.cs.jhu.edu/~mdredze/datasets/sentiment/).

**Comment by bhass1** [comment]
Could you please provide this link near your religion dataset link in the README?

**Comment by marcotcr** [comment]
Good idea. Done.
