### ISSUE TITLE
our_dataset_embeddings.pickle file

### ISSUE THREAD

**Issue by HowardNTUST** [marcotcr/lime-experiments#4]
HI~! Can I request your our_dataset_embeddings.pickle file in order to run data_trusting.py?

**Comment by marcotcr** [comment]
You only need that to run it with the embedding forest.
Our_dataset_embeddings is just a subset of word2vec (I didn't want to load the full model into memory). The file itself is in my old laptop, but [here](https://gist.github.com/marcotcr/6e1a256db25e4d3b498b473eb9472ff0) is a notebook that you can run to generate it yourself for any dataset.
