### ISSUE TITLE
Error when using scikit learn version 0.19

### ISSUE THREAD

**Issue by hereismari** [marcotcr/lime-experiments#5]
AttributeError: 'LogisticRegression' object has no attribute 'transform'

**How to reproduce the error**:

1. Install scikit learn 0.19: pip install 'scikit-learn==0.19' --force-reinstall
2. Run: python evaluate_explanations.py --dataset multi_polarity_books --algorithm l1logreg --explainer random

**How to fix it?**

Install scikit learn 0.16 (not sure which version is the best in this case, but version 0.16 has the transform method) + cross_val_predict

**Comment by marcotcr** [comment]
My bad, I should have added a requirements.txt to make sure people had the right numpy, scipy, sklearn. I did so now, please check the new readme.
