### ISSUE TITLE
Experiment in section 5.2 dataset

### ISSUE THREAD

**Issue by wabc1994** [marcotcr/lime-experiments#9]
There are three version dataset of multi_polarity the link have provide 

- unprocessed.tar.gz
- processed_acl.tar.gz
- processed_star

[![VUheqs.md.png](https://s2.ax1x.com/2019/06/05/VUheqs.md.png)](https://imgchr.com/i/VUheqs)

so which one  you had use in your experiment in  section 5.2 

[![VUhpVI.md.png](https://s2.ax1x.com/2019/06/05/VUhpVI.md.png)](https://imgchr.com/i/VUhpVI)

**Comment by wabc1994** [comment]
@marcotcr

**Comment by marcotcr** [comment]
processed_acl.tar.gz
